<a href="https://colab.research.google.com/github/mistyy12/flyrank-ML/blob/main/notebooks_finished/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mistyy12/flyrank-ML/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [3]:
%pip -q install duckdb huggingface_hub

In [1]:
import os, getpass

# Token order: env var -> Colab Secret -> prompt (last resort).
# Use a Colab Secret named HF_TOKEN (the key panel on the left) so the prompt never
# fires: if Colab reconnects while a getpass prompt is open, the kernel waits on it
# forever ('Resuming execution...') and you have to restart the runtime.
HF_TOKEN = os.environ.get('HF_TOKEN')
if not HF_TOKEN:
    try:
        from google.colab import userdata
        HF_TOKEN = userdata.get('HF_TOKEN')
    except Exception:
        pass
HF_TOKEN = HF_TOKEN or getpass.getpass('Paste your Hugging Face READ token (hf_...): ')

In [2]:
import duckdb

con = duckdb.connect()
con.execute(f"CREATE OR REPLACE SECRET hf (TYPE huggingface, TOKEN '{HF_TOKEN}')")

REL = 'hf://datasets/FlyRank/internship-warehouse'
TABLES = {
    'dim_clients':                f"read_parquet('{REL}/dim_clients.parquet')",
    'dim_content':                f"read_parquet('{REL}/dim_content.parquet')",
    'fact_daily':                 f"read_parquet('{REL}/fact_content_daily_performance/**/*.parquet')",
    'fact_daily_sample':          f"read_parquet('{REL}/fact_content_daily_performance_sample.parquet')",
    'fact_query_90d':             f"read_parquet('{REL}/fact_content_query_90d.parquet')",
}

for name, src in TABLES.items():
    n = con.sql(f'SELECT COUNT(*) FROM {src}').fetchone()[0]
    print(f'{name:22} {n:>12,} rows')

dim_clients                     104 rows
dim_content                 519,606 rows

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

fact_daily               78,835,655 rows
fact_daily_sample        11,694,072 rows
fact_query_90d            2,414,248 rows

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

The unit of analysis here is the content page, where each row represents one unique content_hash_id for a client on a particular dateand contains the features used to evaluate further action in the page. The time window that I'll use is between January 2026 to April 2026 for training data.

In [11]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

# Start with January to test the checks on one partition.
import pandas as pd
results = []

for month in pd.period_range("2026-01", "2026-04", freq="M"):
  source = (
      f"read_parquet('{REL}/"
      f"fact_content_daily_performance/month={month}/*.parquet')"
  )
  result = con.sql(f"""
    SELECT
      COUNT(DISTINCT content_hash_id) AS unique_pages,
      COUNT(DISTINCT client_hash_id) AS unique_clients,
      COUNT(*) AS total_rows,
      MIN(report_date) AS first_date,
      MAX(report_date) AS last_date
    FROM {source}
  """).df()

  #Python: list.insert(position, column_name, value)
  result.insert(0, "month", str(month))
  results.append(result)

monthly_summary = pd.concat(results, ignore_index=True)
display(monthly_summary)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     month  unique_pages  unique_clients  total_rows first_date  last_date
0  2026-01        261984              42     7890817 2026-01-01 2026-01-31
1  2026-02        321546              54     7355108 2026-02-01 2026-02-28
2  2026-03        331437              55     9841378 2026-03-01 2026-03-31
3  2026-04        362172              61    10424730 2026-04-01 2026-04-30

In [12]:
# Example 2 -> January 2025 source
jan2025_source = (
    f"read_parquet('{REL}/"
    "fact_content_daily_performance/month=2025-01/*.parquet')"
)

display(con.sql(f"""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT client_hash_id) AS unique_clients,
        COUNT(DISTINCT content_hash_id) AS unique_pages,
        MIN(report_date) AS first_date,
        MAX(report_date) AS last_date
    FROM {jan2025_source}
""").df())

   total_rows  unique_clients  unique_pages first_date  last_date
0        1297               2           476 2025-01-27 2025-01-31

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [13]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Daily performance fields
display(con.sql(f"""
    DESCRIBE SELECT * FROM {source}
""").df())

# Content metadata fields
display(con.sql(f"""
    DESCRIBE SELECT * FROM {TABLES['dim_content']}
""").df())

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

                   column_name column_type null   key default extra
0               client_hash_id     VARCHAR  YES  None    None  None
1              content_hash_id     VARCHAR  YES  None    None  None
2              keyword_hash_id     VARCHAR  YES  None    None  None
3                  url_hash_id     VARCHAR  YES  None    None  None
4           keyword_char_count      BIGINT  YES  None    None  None
5          keyword_token_count      BIGINT  YES  None    None  None
6               url_char_count      BIGINT  YES  None    None  None
7         content_created_date        DATE  YES  None    None  None
8         content_updated_date        DATE  YES  None    None  None
9                 content_type     VARCHAR  YES  None    None  None
10               search_volume      BIGINT  YES  None    None  None
11                 competition      DOUBLE  YES  None    None  None
12           competition_level     VARCHAR  YES  None    None  None
13                         cpc      DOUBLE  YES  None    None  None
14                 main_intent     VARCHAR  YES  None    None  None
15                   backlinks      BIGINT  YES  None    None  None
16              category_count      BIGINT  YES  None    None  None
17        keyword_created_date        DATE  YES  None    None  None
18               provider_used     VARCHAR  YES  None    None  None
19                  model_used     VARCHAR  YES  None    None  None
20                  char_count      BIGINT  YES  None    None  None
21                  word_count      BIGINT  YES  None    None  None
22         last_optimized_date        DATE  YES  None    None  None
23  optimization_eligible_date        DATE  YES  None    None  None
24                is_published     BOOLEAN  YES  None    None  None
25                  is_deleted     BOOLEAN  YES  None    None  None

1. Feature ->
    "content_created_date","content_updated_date", "gsc_impresssions", "gsc_avg_position", "gsc_sum_position",
    "gsc_clicks",
    "gsc_impressions".
2. Context
-> "content_hash_id", "client_hash_id", "report_date", "month"  

3. Label inputs
-> Outcome-window impressions used to construct something like "is_declining_label"

4. Excluded
-> Outcome-window measurements from model inputs because they reveal the outcome or unused field.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [15]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Define the partitions
paths = [
    f"{REL}/fact_content_daily_performance/month={month}/*.parquet"
    for month in pd.period_range("2026-01", "2026-04", freq="M")
]

# A view defines the source without loading everything into pandas.
con.read_parquet(paths).create_view("contract_daily", replace=True)

┌─────────────┬─────────────────────────┬──────────────────────────┬────────────────┬────────────────┬────────────────────┬────────────────────┬─────────────────┬────────────┬──────────────────┬────────────────────┬───────────────┬──────────────┬───────────┬──────────────────────┬──────────────────────────┬──────────────────┬─────────────────┬───────────────────┬─────────────────┬───────────────┬─────────────┬────────────┬───────────────┬───────────┬────────────┬───────────┬─────────┬──────────┬───────────────┐
│ report_date │     client_hash_id      │     content_hash_id      │ client_has_gsc │ client_has_ga4 │ gsc_data_available │ ga4_data_available │ gsc_impressions │ gsc_clicks │ gsc_sum_position │  gsc_avg_position  │ ga4_pageviews │ ga4_sessions │ ga4_users │ ga4_engaged_sessions │ ga4_total_engagement_sec │ sessions_organic │ sessions_direct │ sessions_referral │ sessions_social │ sessions_paid │ sessions_ai │ ai_chatgpt │ ai_perplexity │ ai_gemini │ ai_copilot │ ai_claude │ ai_meta │ ai_other │ scroll_events │
│    date     │         varchar         │         varchar          │    boolean     │    boolean     │      boolean       │      boolean       │      int64      │   int64    │      int64       │       double       │     int64     │    int64     │   int64   │        int64         │          int64           │      int64       │      int64      │       int64       │      int64      │     int64     │    int64    │   int64    │     int64     │   int64   │   int64    │   int64   │  int64  │  int64   │     int64     │
├─────────────┼─────────────────────────┼──────────────────────────┼────────────────┼────────────────┼────────────────────┼────────────────────┼─────────────────┼────────────┼──────────────────┼────────────────────┼───────────────┼──────────────┼───────────┼──────────────────────┼──────────────────────────┼──────────────────┼─────────────────┼───────────────────┼─────────────────┼───────────────┼─────────────┼────────────┼───────────────┼───────────┼────────────┼───────────┼─────────┼──────────┼───────────────┤
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_8c259838a3dfabe4 │ true           │ false          │ true               │ false              │              16 │          0 │                8 │                0.5 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_5bbd1b5ea9f4d15c │ true           │ false          │ true               │ false              │               1 │          0 │                0 │                0.0 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_65b8a610174a1036 │ true           │ false          │ true               │ false              │              32 │          0 │              154 │             4.8125 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_3fc85bdef381af2d │ true           │ false          │ true               │ false              │              79 │          0 │              161 │  2.037974683544304 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_80071808216aef39 │ true           │ false          │ true               │ false              │            1041 │          0 │             5844 │ 5.6138328530259365 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_9a136f9ba3924c74 │ true           │ false          │ true               │ false              │             442 │          1 │             1055 │ 2.3868778280542986 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_440bb5eb2a519088 │ true           │ false          │ true               │ false              │              88 │          0 │              315 │ 3.5795454545454546 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_fd2a7e03887e7881 │ true           │ false          │ true               │ false              │             237 │          1 │              582 │ 2.4556962025316458 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_5352cb5b4b3d36ce │ true           │ false          │ true               │ false              │              60 │          0 │               24 │                0.4 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│ 2026-01-01  │ client_62f4a7e64f5e0096 │ content_17ff914d33201392 │ true           │ false          │ true               │ false              │               6 │          0 │               10 │ 1.6666666666666667 │             0 │            0 │         0 │                    0 │                        0 │                0 │               0 │                 0 │               0 │             0 │           0 │          0 │             0 │         0 │          0 │         0 │       0 │        0 │             0 │
│     ·       │            ·            │            ·             │  ·             │   ·            │  ·                 │  ·                 │               · │          · │                · │                 ·  │             · │            · │         · │                    · │                        · │                · │               · │                 · │               · │             · │           · │          · │             · │         · │          · │         · │       · │        · │             · │
│     ·       │            ·            │            ·             │  ·             │   ·            │  ·                 │  ·                 │               · │          · │                · │                 ·  │             · │            · │         · │                    · │                        · │                · │               · │                 · │               · │             · │           · │          · │             · │         · │          · │         · │       · │        · │             · │
│     ·       │            ·            │            ·             │  ·             │   ·            │  ·                 │  ·                 │               · │          · │                · │                 ·  │             · │            · │         · │                    · │                        · │                · │               · │                 · │               · │             · │           · │          · │             · │         · │          · │         · │       · │        · │             · │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_c5a88a9f9d075166 │ true           │ false          │ true               │ NULL               │             130 │          0 │              611 │                4.7 │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_3599bbc51547d998 │ true           │ false          │ true               │ NULL               │              27 │          0 │               62 │ 2.2962962962962963 │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_4029131893d7dd3a │ true           │ false          │ false              │ NULL               │               0 │          0 │                0 │               NULL │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_2d2836029986731b │ true           │ false          │ false              │ NULL               │               0 │          0 │                0 │               NULL │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_8e6a4985e20bb4ca │ true           │ false          │ true               │ NULL               │              14 │          0 │              838 │ 59.857142857142854 │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_17012bcacc5df8db │ true           │ false          │ true               │ NULL               │              22 │          0 │               46 │  2.090909090909091 │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_ba11a2d321597637 │ true           │ false          │ false              │ NULL               │               0 │          0 │                0 │               NULL │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_aaccabe20bbbe7bb │ true           │ false          │ true               │ NULL               │             253 │          3 │              481 │  1.901185770750988 │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_c735f4a7209faf21 │ true           │ false          │ true               │ NULL               │             183 │          2 │              616 │  3.366120218579235 │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
│ 2026-01-01  │ client_73cda7b4e4f265ea │ content_5fa7383b9f758667 │ true           │ false          │ true               │ NULL               │              13 │          0 │               20 │ 1.5384615384615385 │          NULL │         NULL │      NULL │                 NULL │                     NULL │             NULL │            NULL │              NULL │            NULL │          NULL │        NULL │       NULL │          NULL │      NULL │       NULL │      NULL │    NULL │     NULL │          NULL │
├─────────────┴─────────────────────────┴──────────────────────────┴────────────────┴────────────────┴────────────────────┴────────────────────┴─────────────────┴────────────┴──────────────────┴────────────────────┴───────────────┴──────────────┴───────────┴──────────────────────┴──────────────────────────┴──────────────────┴─────────────────┴───────────────────┴─────────────────┴───────────────┴─────────────┴────────────┴───────────────┴───────────┴────────────┴───────────┴─────────┴──────────┴───────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         30 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [22]:
# Count -> to check total_rows, unique clients, unique pages in each rows.
# Windows -> first_date, last_date, dates_present (date/time window boundary)
# Grain: missing keys -> how many rows lack at least one field to identify a client-page-date record.
# Measurement availability: how many rows lack confirmed available measurements, even if metrics contain zeros.
# Missing values: how many rows have NULL measurements

window_checks = con.sql("""
    SELECT
        CASE
            WHEN report_date < DATE '2026-04-01'
                THEN 'feature_window'
            ELSE 'outcome_window'
        END AS window_role,

        COUNT(*) AS total_rows,
        COUNT(DISTINCT client_hash_id) AS unique_clients,
        COUNT(DISTINCT content_hash_id) AS unique_pages,


        MIN(report_date) AS first_date,
        MAX(report_date) AS last_date,
        COUNT(DISTINCT report_date) AS dates_present,



        COUNT(*) FILTER (
            WHERE client_hash_id IS NULL
               OR content_hash_id IS NULL
               OR report_date IS NULL
        ) AS missing_grain_fields,


        COUNT(*) FILTER (
            WHERE gsc_impressions IS NULL
        ) AS missing_impressions,

        COUNT(*) FILTER (
            WHERE gsc_clicks IS NULL
        ) AS missing_clicks,

        COUNT(*) FILTER (
            WHERE gsc_avg_position IS NULL
        ) AS missing_position,


        COUNT(*) FILTER (
            WHERE gsc_data_available IS NOT TRUE
        ) AS gsc_unavailable_or_unknown,

        COUNT(*) FILTER (
            WHERE ga4_data_available IS NOT TRUE
        ) AS ga4_unavailable_or_unknown

    FROM contract_daily
    GROUP BY window_role
    ORDER BY first_date
""").df()

display(window_checks)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,window_role,total_rows,unique_clients,unique_pages,first_date,last_date,dates_present,missing_grain_fields,missing_impressions,missing_clicks,missing_position,gsc_unavailable_or_unknown,ga4_unavailable_or_unknown
0,feature_window,25087303,59,349411,2026-01-01,2026-03-31,90,0,98006,98006,16457317,16457316,24412230
1,outcome_window,10424730,61,362172,2026-04-01,2026-04-30,30,0,0,0,6523681,6523670,9900439

In [17]:
#Verify the daily grain. One record per client-page-date in these 4 partitions

display(con.sql("""
    SELECT
        client_hash_id,
        content_hash_id,
        report_date,
        COUNT(*) AS row_count
    FROM contract_daily
    GROUP BY client_hash_id, content_hash_id, report_date
    HAVING COUNT(*) > 1
    LIMIT 5
""").df())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [client_hash_id, content_hash_id, report_date, row_count]
Index: []

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

Overall, this features includes dates used to calculate the outcome (April). Therefore, my Jan-Mar feature window and April outcome window do not overlap.

However, there are some clients that have 120 observed dates, while others have fewer, such as clients with 1 or 11 dates.

Besides that, GSC is available on dates when GA4 is unavailable (GSC-only periods). This unavailable GA4 values cannot be interpreted as zero engagement.

This may cause unbalanced history and overlapping windows, as the data is also taken from last year.

In [24]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
with pd.option_context("display.max_rows", None):
  display(con.sql("""
      SELECT
          client_hash_id,
          MIN(report_date) AS first_date,
          MAX(report_date) AS last_date,
          COUNT(DISTINCT report_date) AS dates_present,
          COUNT(DISTINCT report_date) FILTER (
              WHERE gsc_data_available IS TRUE
          ) AS dates_with_gsc,
          COUNT(DISTINCT report_date) FILTER (
              WHERE ga4_data_available IS TRUE
          ) AS dates_with_ga4
      FROM contract_daily
      GROUP BY client_hash_id
      ORDER BY dates_present, dates_with_ga4
  """).df())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,client_hash_id,first_date,last_date,dates_present,dates_with_gsc,dates_with_ga4
0,client_c353557474475e51,2026-04-30,2026-04-30,1,1,0
1,client_7de9989c909e91a5,2026-04-20,2026-04-30,11,0,6
2,client_9c26c096d6e57253,2026-04-16,2026-04-30,15,2,4
3,client_0b245132bb722950,2026-04-06,2026-04-30,25,19,7
4,client_8ddc46da5414ffd8,2026-04-02,2026-04-30,29,24,0
5,client_06d356715a8ff3b6,2026-04-02,2026-04-30,29,21,25
6,client_e00b29e582949543,2026-03-23,2026-04-30,39,35,37
7,client_810019792c9b8efc,2026-03-20,2026-04-30,42,37,33
8,client_f6f0cdf26d03d7bd,2026-03-19,2026-04-30,43,43,6
9,client_861cdcccf8049915,2026-01-01,2026-02-23,54,52,0
10,client_1d09b519bdde7c7a,2026-01-01,2026-02-24,55,52,0
11,client_835f9123c933bc01,2026-01-01,2026-02-24,55,52,0
12,client_2e65897d94f60220,2026-01-01,2026-02-24,55,53,0
13,client_86ebc2f12c01f586,2026-03-03,2026-04-30,59,47,48
14,client_b77d0d5f08f05e64,2026-03-01,2026-04-30,61,50,43
15,client_7eafe750768f0ac2,2026-02-26,2026-04-30,64,64,39
16,client_2b4306c3ed003f01,2026-02-19,2026-04-30,71,71,0
17,client_e5c2aa26a8598242,2026-02-19,2026-04-30,71,71,52
18,client_157ffe4d4a595515,2026-02-19,2026-04-30,71,71,53
19,client_3f0ce4d44fe94f3d,2026-02-19,2026-04-30,71,71,53
20,client_a80fca3f171ed1de,2026-02-19,2026-04-30,71,71,53
21,client_1a730cb2640a1abf,2026-02-19,2026-04-30,71,71,57
22,client_20259bd6705d81d4,2026-02-19,2026-04-30,71,71,59
23,client_9d54435aabd95a6c,2026-02-17,2026-04-30,73,71,66
24,client_4a18d1793d92fb84,2026-02-17,2026-04-30,73,0,71
25,client_0fa64a184f18a4a0,2026-02-17,2026-04-30,73,71,72
26,client_ccdd78843409c8c7,2026-02-12,2026-04-30,78,73,61
27,client_8dbf3abdf07569e0,2026-01-01,2026-04-30,120,120,0
28,client_a1203ffecad62470,2026-01-01,2026-04-30,120,8,0
29,client_795153d5b7850ccf,2026-01-01,2026-04-30,120,120,0
30,client_599043c0ff13edea,2026-01-01,2026-04-30,120,48,0
31,client_770e8e5faa9cddfe,2026-01-01,2026-04-30,120,0,0
32,client_80ee5b7bd5f4eb89,2026-01-01,2026-04-30,120,0,0
33,client_62f4a7e64f5e0096,2026-01-01,2026-04-30,120,120,0
34,client_08a6a72ff48e62c0,2026-01-01,2026-04-30,120,120,0
35,client_2c32078d69f2cbad,2026-01-01,2026-04-30,120,8,0
36,client_400c21c81c8b46ef,2026-01-01,2026-04-30,120,120,0
37,client_0797ff3a1fc9a6a5,2026-01-01,2026-04-30,120,120,0
38,client_8ae2bfb5aa1ffa1e,2026-01-01,2026-04-30,120,120,0
39,client_19b89ee4fe3db6da,2026-01-01,2026-04-30,120,0,6
40,client_625b6439094e23e4,2026-01-01,2026-04-30,120,0,34
41,client_73cda7b4e4f265ea,2026-01-01,2026-04-30,120,120,38
42,client_3ffa76342f366962,2026-01-01,2026-04-30,120,120,51
43,client_fef1a8f436438636,2026-01-01,2026-04-30,120,120,56
44,client_cd12bcfd98942aa1,2026-01-01,2026-04-30,120,120,59
45,client_764ae36a94e30a25,2026-01-01,2026-04-30,120,38,63
46,client_59256b0571e0c970,2026-01-01,2026-04-30,120,107,66
47,client_0e1acc6cd57b0eba,2026-01-01,2026-04-30,120,120,67
48,client_c182d11e4862a37d,2026-01-01,2026-04-30,120,120,70
49,client_a2eeb8899886adde,2026-01-01,2026-04-30,120,120,70
50,client_def0955f7a377868,2026-01-01,2026-04-30,120,120,71
51,client_a60a11451483af1c,2026-01-01,2026-04-30,120,0,71
52,client_65de48885f4ef01b,2026-01-01,2026-04-30,120,120,71
53,client_2910fd937f0b4d9a,2026-01-01,2026-04-30,120,4,71
54,client_08d2847f24cf89c1,2026-01-01,2026-04-30,120,120,71
55,client_d211cb07b9059bab,2026-01-01,2026-04-30,120,120,71
56,client_f623b01661d4bfe4,2026-01-01,2026-04-30,120,93,84
57,client_b10cb2997d0c7c86,2026-01-01,2026-04-30,120,120,104
58,client_ba65e80a1116ae41,2026-01-01,2026-04-30,120,119,119
59,client_e547b89c05043229,2026-01-01,2026-04-30,120,118,120
60,client_3197e6291363b4db,2026-01-01,2026-04-30,120,120,120
61,client_23a62021009f63c4,2026-01-01,2026-04-30,120,120,120
62,client_2094c6eb080311d5,2026-01-01,2026-04-30,120,120,120
63,client_ff644d8251367cbb,2026-01-01,2026-04-30,120,120,120
64,client_9958f0a7ae1df715,2026-01-01,2026-04-30,120,120,120

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.